name: startit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^7.1.1
  http: ^0.12.2
  dio: ^3.0.10
  image_stack: ^2.0.1
  video_thumbnail: ^0.3.3
  geolocator: ^6.2.1
  geocoder: ^0.2.1
  flutter_google_places: ^0.2.8
  uuid: ^2.2.2
  intl: ^0.16.1
  url_launcher: ^5.7.10
  video_thumbnail_generator: ^0.0.8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  dropdown_date_picker: ^0.1.1+2
  file_picker: ^2.1.7
  path_provider: ^1.6.24
  video_player: ^1.0.1
  shared_preferences: ^0.5.12+4
  google_sign_in: ^4.5.9
  flutter_local_notifications: ^4.0.1+2
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4

  bubble: ^1.2.1
  cached_network_image: ^2.5.1
  date_time_format: ^2.0.1
  firebase_storage: ^5.2.0
  permission_handler: ^4.4.0+hotfix.2
  grouped_list: ^3.7.1
  modal_bottom_sheet: ^1.0.0+1
  selectable_autolink_text: ^2.0.0
  # emoji_picker: ^0.0.3
  # video_thumbnail: ^0.2.5+1
  downloads_path_provider_28: ^0.1.2
  getwidget: ^2.0.3
  open_file: ^3.2.1
  flutter_downloader: ^1.6.1
  share: ^2.0.4
  gradient_fab: ^0.0.1
  chewie: ^0.10.4
  flutter_facebook_login: ^3.0.0
  flutter_facebook_auth: ^2.0.2+1
  emoji_picker: ^0.1.0
  percent_indicator: ^2.1.9
  flutter_dash: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: "assets/images/StartItlogo2.PNG"    
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
